plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5 # 한 페이지에 보여줄 포스트 수
paginate_path: "/page/:num/"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://infinite130.github.io" # the base hostname & protocol for your site
email: skfo3219@gmail.com

social:
  - name: GitHub
    icon: github
    username: infinite130
    url: https://github.com/infinite130
    desc: Follow me on GitHub

# 마크다운 설정
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

